### ISSUE TITLE
javascript callbacks broken

### ISSUE THREAD

**Issue by allenjared** [soomla/cocos2dx-js-store-example#2]
The javascript callbacks for the event handlers never get called (Soomla.js). There appears to be an issue in the ndkbrdige code (iOS) where if no store event handle is registered it just returns instead of continuing and calling the javascript callback - so javascript never sees the events.

But.. if you add any test event handle in cpp to get past that 
soomla::CCStoreEventDispatcher::getInstance()->addEventHandler(handler);

you now get asset errors, unless you define all the store items in cpp as well. But all the examples show doing everything in javascript.. so it just seems broken right now. The way the docs and js example are written seems out of date.

**Comment by sluzky** [comment]
@allenjared closing this, re-open if still relevant
